# Alternative: Use latest versions of all actions
name: Deploy to Azure VM

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install backend dependencies
      run: |
        cd basic-fullstack-app/server
        npm ci --production

    - name: Install frontend dependencies and build
      run: |
        cd frontend
        npm ci
        npm run build
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"

    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp -r basic-fullstack-app/server/ deployment/backend/
        cp -r frontend/build/ deployment/frontend-build/
        tar -czf deployment.tar.gz deployment/
        echo "Deployment package created at $(date)" >> deploy.log

    - name: Deploy to Azure VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        source: "deployment.tar.gz,deploy.log"
        target: "/home/${{ secrets.AZURE_VM_USERNAME }}/deployments/"

    - name: Execute deployment commands on VM
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          cd /home/${{ secrets.AZURE_VM_USERNAME }}/deployments/
          tar -xzf deployment.tar.gz
          echo "=== Deployment started at $(date) ===" >> deploy.log
          
          # Backend deployment
          cd deployment/backend
          npm install --production
          pm2 delete retail-backend 2>/dev/null || true
          pm2 start server.js --name retail-backend
          pm2 save
          echo "Backend deployed" >> ../deploy.log
          
          # Frontend deployment
          sudo rm -rf /home/azureuser/frontend-build
          sudo mv ../frontend-build /home/azureuser/
          sudo chown -R www-data:www-data /home/azureuser/frontend-build
          sudo chmod -R 755 /home/azureuser/frontend-build
          echo "Frontend deployed" >> ../deploy.log
          
          # Restart NGINX
          sudo systemctl restart nginx
          echo "NGINX restarted" >> ../deploy.log
          echo "=== Deployment completed at $(date) ===" >> ../deploy.log

    - name: Download and upload deployment log
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        source: "/home/${{ secrets.AZURE_VM_USERNAME }}/deployments/deploy.log"
        target: "."

    - name: Upload deployment log artifact
      uses: actions/upload-artifact@v4
      with:
        name: deployment-log
        path: deploy.log